Updated scripts

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -2,87 +2,108 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -e "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
-err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; exit "$1"; }
-good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
-info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+err() { echo -e "${color:+\e[31m}[!] $*${color:+\e[0m}" >&2; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*${color:+\e[0m}"; }
+info() { echo -e "${color:+\e[37m}[*] $*${color:+\e[0m}"; }
 long_opt() {
     local arg shift="0"
     case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
     esac
     echo "$arg"
     return $shift
 }
-subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*${color:+\e[0m}"; }
+warn() { echo -e "${color:+\e[33m}[-] $*${color:+\e[0m}"; }
 ### Helpers end
 
 usage() {
     cat <<EOF
 Usage: ${0##*/} [OPTIONS]
 
-Install or uninstall irc script
+DESCRIPTION
+    Install or uninstall $dst.
 
-Options:
-    -d, --dir=INSTALL_DIR    Install to specified directory
-    -h, --help               Display this help message
-    --nocolor                Disable colorized output
-    -u, --uninstall          Uninstall
+OPTIONS
+    -d, --dir=DIR      Install location (default: ~/.local/bin)
+    -h, --help         Display this help message
+        --no-color     Disable colorized output
+    -u, --uninstall    Uninstall
 
 EOF
     exit "$1"
 }
 
-declare -a args deps
+declare -a args
 unset help
 action="install"
-bin="irc"
 color="true"
-install_dir="$HOME/.local/bin"
-
-# Check for missing dependencies
-check_deps
+dir="$HOME/.local/bin"
+dst="irc"
+src="irc"
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        "--") shift && args+=("$@") && break ;;
-        "-d"|"--dir"*) install_dir="$(long_opt "$@")" || shift ;;
+        "--") shift; args+=("$@"); break ;;
+        "-d"|"--dir"*) dir="$(long_opt "$@")" ;;
         "-h"|"--help") help="true" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-u"|"--uninstall") action="uninstall" ;;
         *) args+=("$1") ;;
+    esac
+    case "$?" in
+        0) ;;
+        1) shift ;;
+        *) usage $? ;;
     esac
     shift
 done
 [[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
-# Check for valid params
+# Help info
 [[ -z $help ]] || usage 0
+
+# Check for missing dependencies
+declare -a deps
+deps+=("install")
+deps+=("sed")
+deps+=("sudo")
+check_deps
+
+# Check for valid params
 [[ $# -eq 0 ]] || usage 1
 
 unset sudo
 case "$action" in
     "install")
         info "Installing..."
-        mkdir -p "$install_dir"
-        [[ -w $install_dir ]] || sudo="sudo"
-        $sudo install -m 755 $bin "$install_dir/$bin"
-        $sudo sed -i -e "s#INSTALL_DIR#$(pwd)#g" "$install_dir/$bin"
+        mkdir -p "$dir"
+        [[ -w $dir ]] || sudo="sudo"
+        $sudo install -m 755 "$src" "$dir/$dst"
+        $sudo sed -i -e "s#INSTALL_DIR#$(pwd)#g" "$dir/$dst"
         ;;
     "uninstall")
-        if [[ -f $install_dir/$bin ]]; then
+        if [[ -f $dir/$dst ]]; then
             info "Uninstalling..."
-            [[ -w $install_dir ]] || sudo="sudo"
-            $sudo rm -f "$install_dir/$bin"
+            [[ -w $dir ]] || sudo="sudo"
+            $sudo rm -f "$dir/$dst"
         else
-            errx 2 "$bin is not installed in $install_dir"
+            errx 2 "$dst is not installed in $dir"
         fi
         ;;
     *) usage 3 ;;
diff --git a/irc b/irc
--- a/irc
+++ b/irc
@@ -2,68 +2,85 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -e "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
-err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; exit "$1"; }
-good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
-info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+err() { echo -e "${color:+\e[31m}[!] $*${color:+\e[0m}" >&2; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*${color:+\e[0m}"; }
+info() { echo -e "${color:+\e[37m}[*] $*${color:+\e[0m}"; }
 long_opt() {
     local arg shift="0"
     case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
     esac
     echo "$arg"
     return $shift
 }
-subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*${color:+\e[0m}"; }
+warn() { echo -e "${color:+\e[33m}[-] $*${color:+\e[0m}"; }
 ### Helpers end
 
 usage() {
     cat <<EOF
 Usage: ${0##*/} [OPTIONS] <server>
 
-Create runtime configs and start Weechat
+DESCRIPTION
+    Create runtime configs and start Weechat.
 
-Options:
+OPTIONS
     -a, --no-connect    Disable auto-connect
     -h, --help          Display this help message
-    --nocolor           Disable colorized output
+        --no-color      Disable colorized output
 
 EOF
     exit "$1"
 }
 
-declare -a args deps
+declare -a args
 unset help noconnect
 color="true"
 configs="INSTALL_DIR/configs"
-# deps+=("todo")
 runtime="$configs/runtime"
 template="$configs/template"
-
-# Check for missing dependencies
-check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        "--") shift && args+=("$@") && break ;;
+        "--") shift; args+=("$@"); break ;;
         "-a"|"--no-connect") noconnect="--no-connect" ;;
         "-h"|"--help") help="true" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         *) args+=("$1") ;;
+    esac
+    case "$?" in
+        0) ;;
+        1) shift ;;
+        *) usage $? ;;
     esac
     shift
 done
 [[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
-# Check for valid params
+# Help info
 [[ -z $help ]] || usage 0
+
+# Check for missing dependencies
+declare -a deps
+deps+=("weechat")
+check_deps
+
+# Check for valid params
 [[ $# -eq 1 ]] || usage 1
 
 # These are needed at a minimum
